### ISSUE TITLE
Latest KeyCloak

### ISSUE THREAD

**Issue by malishahi** [dasniko/keycloak-reactjs-demo#1]
Hi,

I am wondering if this code works with the latest version of KeyCloak. As I understand it leverages Javascript adaptor of KeyCloak, am I right?

Thanks,
Mehdi

**Comment by dasniko** [comment]
It should work.
And yes, it uses the Keycloak JS adapter.
The last time I tested it, was with KC 2.3.x, as it is comitted.
So far, I didn't test it with 2.5.x, but I don't know a reason why it shouldn't work.

**Comment by malishahi** [comment]
Hi Niko:

Thanks for the note.

We have used the following code:


Code : 
let KeycloakConfig = {
  "realm": "waziup",
  "realm-public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiIzXeJ5OxrvawVoNXz+4zCBX66pki5PYltqggPYkt45Q60zBtK5ZS5vVecBBJ10Ae4NxKCRE9iNr0COmabK+a13e1FYYrsj1tN0SfQC2cKuI1WWc7LO7gEycS4+sauOjzdMYTkmLwj2GhIxo1vuhcBqyLV2NmSBEAqfGntjkI6kTRU3QlAlIp0NsNpc6ZYn9TPE+zhcr3GBruCDLbg0yYDtpK5GxK2gh8C4uaq9e55pPIVKo3FjX+5iYUJ6zluu1oafcec3MYRtYnbyOIQpkvpeUheqif5SKATeVgn4jyhEcH03zY+tiFe0p6spivT4gzxp9kkrKEnX0CsvFprQH6QIDAQAB",
  "url": "http://localhost:8180/auth",
  "ssl-required": "none",
  "resource": "dashboard",
  "clientId": "dashboard",
  "credentials": {
    "secret": "fc6bc278-aee1-4cd5-83bc-cfa3c73d9c8b"
  }
}

let kc = Keycloak(KeycloakConfig);
  console.log(kc);
kc.init({onLoad: 'check-sso'}).success(authenticated => {
  if (authenticated) {
   store.getState().keycloak = kc;
    setInterval(() => {
      kc.updateToken(10).error(() => kc.logout());
    }, 10000);
    ReactDOM.render(
      <Provider store={store}>
        <Router history={history} routes={routes} />
      </Provider>
      , document.getElementById('root'))
  } else {
    // show possibly other page here...
    kc.login();
  }
});

But it has failed with the followinng errors:

Context Path:
/auth

Servlet Path:

Path Info:
/realms/waziup/protocol/openid-connect/login-status-iframe.html

Query String:
null

Stack Trace
java.lang.RuntimeException: request path: /auth/realms/waziup/protocol/openid-connect/login-status-iframe.html
org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:75)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by dasniko** [comment]
This seems to be related to wrong configuration at some point.
Nothing I can help on without having a look at all resources (no, this is not a request to post all of your config).
Perhaps the Keycloak mailinglist is the right place to ask!?

**Comment by malishahi** [comment]
Thanks a lot Niko for the note.

Reading KeyCloak document for JS adaptor I've resolved this problem.
Now app shows the login page, after logining into app with KC, there is an infinite loop.
Any idea on this? Sorry I am asking this question here, but from Internet it is not easy to find the problem.

**Comment by dasniko** [comment]
Infinite loop is not good... and to all that mess, this can have several different causes.
Sounds weird, but have you re-started KC and the app?
This sometimes helps me.
Also, setting debugging breakpoints in the JS code and verify, what's going on.
Unfortunately I don't know a "when infinite loop, then do ..."

**Comment by malishahi** [comment]
We were using old KC. Updating to latest KC, our problem has been resolved. Thanks.
