### ISSUE TITLE
`Loading application...` ERROR

### ISSUE THREAD

**Issue by AustinDeric** [dasniko/keycloak-reactjs-demo#10]
I log into keycloak and i get redirected back to the web app and it says

Loading application...

here is my console output:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://[redacted]:8443/auth/realms/[redacted]/protocol/openid-connect/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

XML Parsing Error: no root element found
Location: https://[redacted]:8443/auth/realms/[redacted]/protocol/openid-connect/login-status-iframe.html/init?client_id=[redacted]
Line Number 1, Column 1:

my use case is that i have keycloak running on a server at https://somesite.com and i have this code running locally.  It appears that the origin url is configurable with the admin console, i just can't figure out what to put into the origin and redirect url fields to make it work.

**Comment by AustinDeric** [comment]
My temporary fix was to enter `*` in the Web Origins field of the realm's client settings.  Please note that this is BAD PRACTICE and allows attacks impersonating the user from any origin.

I tried http://localhost:3000/* and that didn't work.

some info on the web origins field which configures CORS:
https://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients

**Comment by dasniko** [comment]
This is Keycloak configuration related, please see my comment on the [README.md](https://github.com/dasniko/keycloak-reactjs-demo/blob/master/README.md)
