### ISSUE TITLE
Change BrowserHistory to HashHistory

### ISSUE THREAD

**Issue by Tilican** [dasniko/keycloak-reactjs-demo#12]
Hi,
I want to use HashHistory instead of BrowserHistory, but the app always redirect me ...
Have you got a trick to by pass this thing ?
Thx :)

**Comment by dasniko** [comment]
Unfortunately I can't help here, sorry.
I didn't use HashHistory yet and I likely won't do ever, as I think real paths are a way better thing than urls with hashes... but that's another story.
