### ISSUE TITLE
How to get access and identity tokens with ReactJS

### ISSUE THREAD

**Issue by malishahi** [dasniko/keycloak-reactjs-demo#2]
Hi,

I was wondering if there are example codes on getting access and identity tokens with ReactJS.

Thanks,
Mehdi

**Comment by dasniko** [comment]
This is not related to this example/demo nor to ReactJS, as it depends on how you store the `Keycloak` object in your app. There are multiple ways to do it.
For methods, how to access the tokens in the `Keyclaok` object, visit Keycloak documentation at https://keycloak.gitbooks.io/documentation/securing_apps/topics/oidc/javascript-adapter.html
