### ISSUE TITLE
Infinite reload issue with chrome browser

### ISSUE THREAD

**Issue by Joban1992** [dasniko/keycloak-reactjs-demo#3]
Try to run the app with my KeyCloak Setup. It works fine with with all other browser except Chrome. After authentication it reloads again and again.

**Comment by dasniko** [comment]
This is not related to this demo, as this might be an issue with Chrome or the Keycloak JS library, which had a bug in one of the previous versions. Please refer to the official Keycloak documentation or the mailing-list, if the issue still occurs.

**Comment by Joban1992** [comment]
Fixed this issue. Issue was not with chrome.  Issue was because of iframe. KeyCloak append iframe in your browser window and iframe then sends a request to KeyCloak server for authentication before response comes back and iframe update parent window about response KeyCloak library was appending one more iframe, which result in infinite loop. So I just added condition in KeyCloak library , if iframe is already in window do not append new iframe. 

Thanks

**Comment by cadaniel** [comment]
@Joban1992 I'm having the same problem with the reloads, what exactly did you fix? Every 10 seconds or so I get an alert saying authenticated

`
    const keycloak = Keycloak(
      {
        url: "/auth",
        realm : "...",
        clientId: "...",
        resource: "...",
        'public-client': true,
        'ssl-required': "none"
      }
    );
    keycloak.init({ onLoad: "check-sso" }).success(function(authenticated) {
      alert(authenticated ? 'authenticated' : 'not authenticated');
    }).error(function() {
      alert('failed to initialize');
    });
  }
`

**Comment by djmason9** [comment]
The way to fix this w/o changing code is to init it like this.  keycloak.init({onLoad: 'login-required',"checkLoginIframe" : false})
where checkloginiframe is disabled

**Comment by sumalya** [comment]
Thanks @djmason9 . It worked!

**Comment by ajinkyabapat1** [comment]
> The way to fix this w/o changing code is to init it like this. keycloak.init({onLoad: 'login-required',"checkLoginIframe" : false})
> where checkloginiframe is disabled
@djmason9 i came across this infinite reload recently , i used your technique to solve this issue. but same code was working fine without adding [checkLoginIframe" : false] !! any idea why sudden it started refreshing the page ?

**Comment by rodgersgb** [comment]
> any idea why sudden it started refreshing the page ?

I just started getting this issue too. It was working fine until Chrome crashed recently and I restarted (rarely restart Chrome) and it pulled some updates. I'm wondering if it's related to Chrome's recent SameSite changes. Based on my logs, the token is received from Keycloak after login, but after redirect back to my app page, the refresh of the token fails with a 400 error. And this cycle repeats over and over.

(!) A cookie associated with a cross-site resource at https://mykeycloak/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
[KEYCLOAK] Estimated time difference between browser and server is 0 seconds
(3) [KEYCLOAK] Refreshing token: token expired
(x) POST https://mykeycloak/auth/realms/myrealm/protocol/openid-connect/token 400
(!) [KEYCLOAK] Failed to refresh token

**Comment by daniellaera** [comment]
> The way to fix this w/o changing code is to init it like this. keycloak.init({onLoad: 'login-required',"checkLoginIframe" : false})
> where checkloginiframe is disabled

excellent
