### ISSUE TITLE
Code gets a 403 from Keycloak

### ISSUE THREAD

**Issue by stdunbar** [dasniko/keycloak-reactjs-demo#33]
Running this code against Keycloak 16.1.0 results in a 403 forbidden.  The request looks like:

https://myauthserver.example.com/auth/realms/realm-name/protocol/openid-connect/login-status-iframe.html/init?client_id=the-client&origin=http://localhost:3000

Once that happens you get an undefined error in index.js.  I have tried both 15.0.2 and 16.0.1 for the keycloak-js dependency in package.json

**Comment by stdunbar** [comment]
In Keycloak, for the client you're using, set "Web Origins" to "*" and it takes care of this.  Sorry if I missed it in your instructions.  It's hard to grep a video.

**Comment by dasniko** [comment]
Having `*` as a placeholder in Web-Origins is against the spec, as `*` is not specified and thus not guaranteed to work.

If you read the Keycloak docs, you will see that Keycloak provides a "special" wildcard `+` for the Web-Origins, which means to use all hosts from "Valid Redirect URIs" as valid Web-Origins.

Always configure your CORS setting properly, never use the `*` wildcard!
