### ISSUE TITLE
anyone can provide a sample realm JSON file for import?

### ISSUE THREAD

**Issue by mingderwang** [dasniko/keycloak-reactjs-demo#4]
as subject.
Thanks in advance

**Comment by iiitmahesh** [comment]
**Go to keyclaock admin console :**  relam=> clients=> installation => Keycloak ODIC JSON

sample realm 
```
{
  "realm": "test",
  "auth-server-url": "http://test.com/auth",
  "ssl-required": "external",
  "resource": "test-dev",
  "public-client": true
}
```

you can close the issue if you're clear about this..!

**Comment by dasniko** [comment]
*lol*
This is really the smallest possible realm file with which you can't do anything meaningful (as no clients/users are configured).
But ok, it answered the question.
